### ISSUE TITLE
`choice` is not an accepted keyword in the schema

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#472]
This given example is not a valid yaml based on the schema:
```yaml
- number: 445
  content:
    - text: |
        You climb up, and squeeze through an open window into along hall.
        Thin wires are stretched across the room, 
        but you are an able enough rogue to crawl through without touching any of them and setting off possible traps or alarms.
        Inside the temple, it is cool and dark, filled with an unearthly stillness.
        Suddenly, the temple doors are flung open, and two figures lumber into the room.
        You realize with a thrill of horror that the bull-headed iron statues outside the gates have come to life. 
        They are golems, set here to guard the temple.
    - choice:
        - text: Run for your life
          turnTo: 349
        - text: Fight them
          turnTo: 569
```
I think `choice` doesn't exist entirely...
