### ISSUE TITLE
Support tickbox actions and checks in YAML Schema

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#476]
Please support
```yaml
if:
  isTickBoxDone: true
then:
  ...
```
and
```yaml
checkTickBox: true
```
in content and everywhere else
