### ISSUE TITLE
How should we store the section data?

### ISSUE THREAD

**Issue by Nilstrieb** [keykey7/fabbwled#72]
**Describe the solution you'd like**

Right now we have Java classes

https://github.com/keykey7/fabbwled/blob/2e73b8cb43f5b5831b8113e529e3af3cba9aa56a/fabbwled-backend/src/main/java/ch/bbw/fabbwled/lands/book/book1/Section15.java#L26-L35

which is a possibility but also not great. It has a lot of boilerplate, especially with the `onClick` part. It also causes us to have 600 small files which is a lot. But Java code is checked statically, which is less prone to mistakes.

One alternative I've tried out is some YAML, like this:
```yaml
- number: 15
  content:
    - text: Three drunken army officers...
    - if:
        hasTitle: "Protector of Sokara"
      then:
        - turnTo: 542
      else:
        - text: If not, read on.
        - choice:
          - text: Step out of the way
            then:
              - turnTo: 44
          - text: Return the insult
            then:
              - turnTo: 266
```

The YAML is a lot shorter and smaller. It also allows for many cases within the same file. It has no redundancy and is fully declarative. But it's less flexible and we'd have to implement every weird little system for the YAML. But that's also the case for Java so I think that's fine.

Originally I thought that Java would be the best solution but now that I've played with it a bit I do like the YAML. Although the Java could certainly be improved as well to still be Java but nicer.
